IF NOT EXISTS (SELECT * FROM sys.objects O JOIN sys.schemas S ON O.schema_id = S.schema_id WHERE O.NAME = '[loans]' AND O.TYPE = 'U' AND S.NAME = '[dbo]')
CREATE TABLE [dbo].[loans2]
	(
	 [id] nvarchar(4000),
	 [member_id] nvarchar(4000),
	 [loan_amnt] bigint,
	 [funded_amnt] bigint,
	 [funded_amnt_inv] bigint,
	 [term] nvarchar(4000),
	 [int_rate] float,
	 [installment] float,
	 [grade] nvarchar(4000),
	 [sub_grade] nvarchar(4000),
	 [emp_title] nvarchar(4000),
	 [emp_length] nvarchar(4000),
	 [home_ownership] nvarchar(4000),
	 [annual_inc] bigint,
	 [verification_status] nvarchar(4000),
	 [issue_d] nvarchar(4000),
	 [loan_status] nvarchar(4000),
	 [pymnt_plan] nvarchar(4000),
	 [url] nvarchar(4000),
	 [descp] nvarchar(max),
	 [purpose] nvarchar(4000),
	 [title] nvarchar(4000),
	 [zip_code] nvarchar(4000),
	 [addr_state] nvarchar(4000),
	 [dti] float,
	 [delinq_2yrs] bigint,
	 [earliest_cr_line] nvarchar(4000),
	 [inq_last_6mths] bigint,
	 [mths_since_last_delinq] bigint,
	 [mths_since_last_record] bigint,
	 [open_acc] bigint,
	 [pub_rec] bigint,
	 [revol_bal] bigint,
	 [revol_util] float,
	 [total_acc] bigint,
	 [initial_list_status] nvarchar(4000),
	 [out_prncp] float,
	 [out_prncp_inv] float,
	 [total_pymnt] float,
	 [total_pymnt_inv] float,
	 [total_rec_prncp] float,
	 [total_rec_int] float,
	 [total_rec_late_fee] float,
	 [recoveries] float,
	 [collection_recovery_fee] float,
	 [last_pymnt_d] nvarchar(4000),
	 [last_pymnt_amnt] float,
	 [next_pymnt_d] nvarchar(4000),
	 [last_credit_pull_d] nvarchar(4000),
	 [collections_12_mths_ex_med] bigint,
	 [mths_since_last_major_derog] bigint,
	 [policy_code] bigint,
	 [application_type] nvarchar(4000),
	 [annual_inc_joint] bigint,
	 [dti_joint] float,
	 [verification_status_joint] nvarchar(4000),
	 [acc_now_delinq] bigint,
	 [tot_coll_amt] bigint,
	 [tot_cur_bal] bigint,
	 [open_acc_6m] bigint,
	 [open_act_il] bigint,
	 [open_il_12m] bigint,
	 [open_il_24m] bigint,
	 [mths_since_rcnt_il] bigint,
	 [total_bal_il] bigint,
	 [il_util] bigint,
	 [open_rv_12m] bigint,
	 [open_rv_24m] bigint,
	 [max_bal_bc] bigint,
	 [all_util] bigint,
	 [total_rev_hi_lim] bigint,
	 [inq_fi] bigint,
	 [total_cu_tl] bigint,
	 [inq_last_12m] bigint,
	 [acc_open_past_24mths] bigint,
	 [avg_cur_bal] bigint,
	 [bc_open_to_buy] bigint,
	 [bc_util] float,
	 [chargeoff_within_12_mths] bigint,
	 [delinq_amnt] bigint,
	 [mo_sin_old_il_acct] bigint,
	 [mo_sin_old_rev_tl_op] bigint,
	 [mo_sin_rcnt_rev_tl_op] bigint,
	 [mo_sin_rcnt_tl] bigint,
	 [mort_acc] bigint,
	 [mths_since_recent_bc] bigint,
	 [mths_since_recent_bc_dlq] bigint,
	 [mths_since_recent_inq] bigint,
	 [mths_since_recent_revol_delinq] bigint,
	 [num_accts_ever_120_pd] bigint,
	 [num_actv_bc_tl] bigint,
	 [num_actv_rev_tl] bigint,
	 [num_bc_sats] bigint,
	 [num_bc_tl] bigint,
	 [num_il_tl] bigint,
	 [num_op_rev_tl] bigint,
	 [num_rev_accts] bigint,
	 [num_rev_tl_bal_gt_0] bigint,
	 [num_sats] bigint,
	 [num_tl_120dpd_2m] bigint,
	 [num_tl_30dpd] bigint,
	 [num_tl_90g_dpd_24m] bigint,
	 [num_tl_op_past_12m] bigint,
	 [pct_tl_nvr_dlq] float,
	 [percent_bc_gt_75] float,
	 [pub_rec_bankruptcies] bigint,
	 [tax_liens] bigint,
	 [tot_hi_cred_lim] bigint,
	 [total_bal_ex_mort] bigint,
	 [total_bc_limit] bigint,
	 [total_il_high_credit_limit] bigint,
	 [revol_bal_joint] bigint,
	 [sec_app_earliest_cr_line] nvarchar(4000),
	 [sec_app_inq_last_6mths] bigint,
	 [sec_app_mort_acc] bigint,
	 [sec_app_open_acc] bigint,
	 [sec_app_revol_util] float,
	 [sec_app_open_act_il] bigint,
	 [sec_app_num_rev_accts] bigint,
	 [sec_app_chargeoff_within_12_mths] bigint,
	 [sec_app_collections_12_mths_ex_med] bigint,
	 [sec_app_mths_since_last_major_derog] bigint,
	 [hardship_flag] nvarchar(4000),
	 [hardship_type] nvarchar(4000),
	 [hardship_reason] nvarchar(4000),
	 [hardship_status] nvarchar(4000),
	 [deferral_term] nvarchar(4000),
	 [hardship_amount] nvarchar(4000),
	 [hardship_start_date] nvarchar(4000),
	 [hardship_end_date] nvarchar(4000),
	 [payment_plan_start_date] nvarchar(4000),
	 [hardship_length] nvarchar(4000),
	 [hardship_dpd] nvarchar(4000),
	 [hardship_loan_status] nvarchar(4000),
	 [orig_projected_additional_accrued_interest] nvarchar(4000),
	 [hardship_payoff_balance_amount] nvarchar(4000),
	 [hardship_last_payment_amount] nvarchar(4000),
	 [disbursement_method] nvarchar(4000),
	 [debt_settlement_flag] nvarchar(4000),
	 [debt_settlement_flag_date] nvarchar(4000),
	 [settlement_status] nvarchar(4000),
	 [settlement_date] nvarchar(4000),
	 [settlement_amount] nvarchar(4000),
	 [settlement_percentage] nvarchar(4000),
	 [settlement_term] nvarchar(4000)
	)
WITH
	(
	DISTRIBUTION = ROUND_ROBIN,
	 HEAP
	 -- CLUSTERED COLUMNSTORE INDEX
	)
GO

--Uncomment the 4 lines below to create a stored procedure for data pipeline orchestration​
--CREATE PROC bulk_load_[loans]
--AS
--BEGIN
COPY INTO [dbo].[loans2]
(id 1, member_id 2, loan_amnt 3, funded_amnt 4, funded_amnt_inv 5, term 6, int_rate 7, installment 8, grade 9, sub_grade 10, emp_title 11, emp_length 12, home_ownership 13, annual_inc 14, verification_status 15, issue_d 16, loan_status 17, pymnt_plan 18, url 19, descp 20, purpose 21, title 22, zip_code 23, addr_state 24, dti 25, delinq_2yrs 26, earliest_cr_line 27, inq_last_6mths 28, mths_since_last_delinq 29, mths_since_last_record 30, open_acc 31, pub_rec 32, revol_bal 33, revol_util 34, total_acc 35, initial_list_status 36, out_prncp 37, out_prncp_inv 38, total_pymnt 39, total_pymnt_inv 40, total_rec_prncp 41, total_rec_int 42, total_rec_late_fee 43, recoveries 44, collection_recovery_fee 45, last_pymnt_d 46, last_pymnt_amnt 47, next_pymnt_d 48, last_credit_pull_d 49, collections_12_mths_ex_med 50, mths_since_last_major_derog 51, policy_code 52, application_type 53, annual_inc_joint 54, dti_joint 55, verification_status_joint 56, acc_now_delinq 57, tot_coll_amt 58, tot_cur_bal 59, open_acc_6m 60, open_act_il 61, open_il_12m 62, open_il_24m 63, mths_since_rcnt_il 64, total_bal_il 65, il_util 66, open_rv_12m 67, open_rv_24m 68, max_bal_bc 69, all_util 70, total_rev_hi_lim 71, inq_fi 72, total_cu_tl 73, inq_last_12m 74, acc_open_past_24mths 75, avg_cur_bal 76, bc_open_to_buy 77, bc_util 78, chargeoff_within_12_mths 79, delinq_amnt 80, mo_sin_old_il_acct 81, mo_sin_old_rev_tl_op 82, mo_sin_rcnt_rev_tl_op 83, mo_sin_rcnt_tl 84, mort_acc 85, mths_since_recent_bc 86, mths_since_recent_bc_dlq 87, mths_since_recent_inq 88, mths_since_recent_revol_delinq 89, num_accts_ever_120_pd 90, num_actv_bc_tl 91, num_actv_rev_tl 92, num_bc_sats 93, num_bc_tl 94, num_il_tl 95, num_op_rev_tl 96, num_rev_accts 97, num_rev_tl_bal_gt_0 98, num_sats 99, num_tl_120dpd_2m 100, num_tl_30dpd 101, num_tl_90g_dpd_24m 102, num_tl_op_past_12m 103, pct_tl_nvr_dlq 104, percent_bc_gt_75 105, pub_rec_bankruptcies 106, tax_liens 107, tot_hi_cred_lim 108, total_bal_ex_mort 109, total_bc_limit 110, total_il_high_credit_limit 111, revol_bal_joint 112, sec_app_earliest_cr_line 113, sec_app_inq_last_6mths 114, sec_app_mort_acc 115, sec_app_open_acc 116, sec_app_revol_util 117, sec_app_open_act_il 118, sec_app_num_rev_accts 119, sec_app_chargeoff_within_12_mths 120, sec_app_collections_12_mths_ex_med 121, sec_app_mths_since_last_major_derog 122, hardship_flag 123, hardship_type 124, hardship_reason 125, hardship_status 126, deferral_term 127, hardship_amount 128, hardship_start_date 129, hardship_end_date 130, payment_plan_start_date 131, hardship_length 132, hardship_dpd 133, hardship_loan_status 134, orig_projected_additional_accrued_interest 135, hardship_payoff_balance_amount 136, hardship_last_payment_amount 137, disbursement_method 138, debt_settlement_flag 139, debt_settlement_flag_date 140, settlement_status 141, settlement_date 142, settlement_amount 143, settlement_percentage 144, settlement_term 145)
FROM 'https://azureaihackathon.dfs.core.windows.net/azureaihackathon/loan.csv'
WITH
(
	FILE_TYPE = 'CSV'
	,MAXERRORS = 1000
	,FIRSTROW = 2
	,ERRORFILE = 'https://azureaihackathon.dfs.core.windows.net/azureaihackathon/'
	,IDENTITY_INSERT = 'OFF'
)
--END
GO

SELECT TOP 100 * FROM [dbo].[loans]
GO